### ISSUE TITLE
.expo-sharedはpushしなくてOKです！

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#1]
# 以下２点注文です。
- .expo-sharedのpushはしなくていいので、.gitignoreへ追記しておいてください。
- もし余裕があれば、pushした.expo-sharedも消しておいてください！

**Comment by asagaorino0** [comment]
githubから.expo-sharedに消えていただきました。ちーーーん。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
