### ISSUE TITLE
React.useStateとかReact.useEffectとかについて

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#10]
#importして使用した方がコードの可読性が上がります。
ThirdScreen.tsxで、React.useEffectとかReact.useStateと使用していますが、最上部で
```
import React, {useState,useEffect} from 'react'
```
とし、useEffect,useStateとReact.を書かずに使用したほうが今後のコードの可読性が上がります。
なるべく共通因数はまとめて、コードの記述量を減らしていきましょう！

チームにもよりますが、1コンポーネントで100行以内と決めているチームが多いです。
コードの行数も少しづつ減らせるように工夫してみてください！

**Comment by asagaorino0** [comment]
了解しました。
行数も少なくするようにがんばります。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
