### ISSUE TITLE
firebase.tsにuseStateとuseContextをimportしているのはなぜでしょうか

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#11]
# firebase.tsにuseStateとuseContextをimportしているのはなぜでしょうか
題意の通りですが、恐らく警告がでている状態かと存じます。
push前になるべくエラーや警告はクリアにしておいてください！

よろしくお願いいたします。

**Comment by asagaorino0** [comment]
なぜだか忘れました。
警告は出ていませんが、削除します。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
