### ISSUE TITLE
typeについて

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#12]
#typeでtypesディレクトリにあるtypeとそうでないtypeがありますが、なにかすみ分けはありますか？
なにか明確な意図があれば教えてください！

なにもなければ、なるべくtypes/ディレクトリに格納するのが良いと思います。

**Comment by asagaorino0** [comment]
意図はないです。types/ディレクトリに格納してみます！

**Comment by SatakeYusuke19920527** [comment]
承知しました！
Closeをお願いします。
