### ISSUE TITLE
airbnbのスタイルガイドを是非参考にしてみてください！

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#13]
#スタイルガイド
airbnbという企業がReactの書き方をこうしましょうね。というスタイルガイドを書いてくれました。
https://github.com/airbnb/javascript/tree/master/react　

一読する価値があるドキュメントなので、共有致します。

**Comment by asagaorino0** [comment]
うっ、ありがとうございます。
めちゃ参考になります。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
