### ISSUE TITLE
StarSet.tsxについて

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#18]
これなんですか？

平均値はサーバサイドで計算しましょう！

**Comment by asagaorino0** [comment]
StarSet.tsxは平均値の時に使うつもりだったと思っていましたが、
review作成時にポチっとするアイテムでした😅ので、このまま採用します。

平均値の計算は、別途サーバーサイドで行います。

**Comment by SatakeYusuke19920527** [comment]
承知です！
