### ISSUE TITLE
Componentsディレクトリを作成しましょう！

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#2]
# ディレクトリ階層について
現時点では、Screensの中に全ての部品が入っていると思います。

それを、xxxScreen.tsxとScreenが付くものだけを、Screenディレクトリに配置し、
他のファイルはComponentsディレクトリを作成して、そちらに移動させましょう！

ご対応よろしくお願いいたします。

**Comment by asagaorino0** [comment]
componentsを作成して、Screen以外のファイルを移動しました。

**Comment by SatakeYusuke19920527** [comment]
お疲れ様です！
