### ISSUE TITLE
firestoreのimportはlib/firebase.ts1カ所にしたほうが良いです。

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#4]
# リファクタリング
UploadScreen.tsx3行目でimport "firebase/firestore";をしていますが、
せっかくlib/firebase.tsでfirestoreのimportをしているので、
lib/firebase.tsへ以下を記載して、各コンポーネントで使いまわしたほうが良いです。
> export const firestore = firebase.firestore()

ご対応よろしくお願いいたします。

**Comment by asagaorino0** [comment]
firestoreをlib/firebase.tsからのimportに修正しました。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
