### ISSUE TITLE
const styles = StyleSheet.createはFunctionの上か下かどっちに実装するか統一した方がいいです。

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#6]
# リファクタリング希望
Card.tsxではFunctionの上に、AScreen.tsxではFunctionの下にstyleを実装していますが、
統一した方が後々見やすくなります！

ご対応よろしくお願いいたします。

**Comment by asagaorino0** [comment]
私も気になってました(^_^;)
下に統一しました。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
