### ISSUE TITLE
Screen名はわかりやすいものに変更してください。

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#7]
# Screen名をわかりやすくしたいです。
今、AScreen.tsxやDScreen.tsxがありますが、命名規則として名前を見て何をするファイルかわかるのがベストです。
お時間ある時に是非、修正してください。

## 早めに修正しておいたほうがよさそうです。

**Comment by asagaorino0** [comment]
DScreen.tsxを改名しました。AScreen.tsxは消えていただきました。

**Comment by SatakeYusuke19920527** [comment]
(｀・ω・´)b
