### ISSUE TITLE
SubScreen.tsxのconst db = firebase.firestore()はfirebase.tsのexportを使いましょう！

### ISSUE THREAD

**Issue by SatakeYusuke19920527** [asagaorino0/log_app#8]
# リファクタリング
- SubScreen.tsxのconst db = firebase.firestore()はlib/firebase.tsでexportしているので、それをimportして使用しましょう。
- firebase.auth()もlib/firebase.tsでauthをexportしているので、それを使用していただければと存じます。

**Comment by asagaorino0** [comment]
SubScreen.tsxとDetailScreen.tsxのfirebase.firestore()を修正しました。
